# Generated by Django 3.2 on 2021-05-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='locals.local')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField(choices=[(1, 'Leader'), (2, 'Secretary'), (3, 'Organizing Secretary'), (4, 'Financial Secretary'), (5, 'Prayer'), (6, 'Evangelism'), (7, 'Member')], default=7)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='locals.local')),
            ],
        ),
    ]
